$(document).ready(function(){
    $(".klik").click(function(){
        $(".open-close").slideToggle("slow");
    });
});
$(document).ready(function(){
    $(".klik_nav").click(function(){
        $(".buka_tutup").slideToggle("slow");
    });
});